server:
  port : 80

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            clientId: ${AUTH0_CLIENT_ID:}
            clientSecret: ${AUTH0_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
          keycloak:
            clientId: ${KC_CLIENT_ID:}
            clientSecret: ${KC_CLIENT_SECRET:}
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://sylwesterg.eu.auth0.com/
          keycloak:
            issuer-uri: http://well-known.org:8080/auth/realms/well-known

logging:
  level:
    root: TRACE