server:
  port : 80

spring:
  security:
    oauth2:
      client:
        registration:
          auth0:
            clientId: ******
            clientSecret: ******
            scope:
              - openid
              - profile
              - email
        provider:
          auth0:
            # trailing slash is important!
            issuer-uri: https://sylwesterg.eu.auth0.com/